### ISSUE TITLE
Project experiment page outdated

### ISSUE THREAD

**Issue by tancou** [terrygonguet/site-perso#1]
Hi

References of the next IBD website outdated.

https://github.com/terrygonguet/site-perso/blob/719ed71afd44f8bd03d14f02630bbe2ac1d6f28e/src/data/data.js#L161-L166

https://github.com/terrygonguet/site-perso/blob/719ed71afd44f8bd03d14f02630bbe2ac1d6f28e/src/routes/projects/experiment.svelte#L38-L40

**Comment by terrygonguet** [comment]
Indeed, thanks.
Fixed in #2.
